version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:12.22.7-bullseye-browsers-legacy
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "adding git configs"
      - run: git config user.email "badrri1995@gmail.com"
      - run: git config user.name "ci-build-bot"
      - run: echo "deploying to github-pages"
      - run: npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "97:f7:6b:3b:74:40:01:11:b9:96:54:ac:6a:66:ae:c5"
workflows:
  version: 2
  build_app:
    jobs:
      - build_and_deploy