version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.22.7-bullseye-browsers-legacy
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
workflows:
  version: 2
  build_app:
    jobs:
      - build