version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:12.22.7-bullseye-browsers-legacy
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "adding git configs"
      - run: git config user.email "badrri1995@gmail.com"
      - run: git config user.name "ci-build-bot"
      - add_ssh_keys:
          fingerprints:
            - "4c:9a:11:aa:ca:6b:45:d0:18:91:5b:d0:f6:95:79:9b"
      - run: echo "deploying to github-pages"
      - run: npm run deploy
workflows:
  version: 2
  build_app:
    jobs:
      - build_and_deploy
      - deploy_to_production:
          requires:
            - build_and_deploy
          filters:
            branches:
              only:
                - master