version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:12.22.7-bullseye-browsers-legacy
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: echo "adding git configs"
      - run: git config user.email "badrri1995@gmail.com"
      - run: git config user.name "ci-build-bot"
      - run: echo "deploying to github-pages"
      - run: npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "43:b9:be:74:46:20:d9:b8:21:68:f8:de:2e:21:03:18"
workflows:
  version: 2
  build_app:
    jobs:
      - build_and_deploy