export const CHANGE_SEARCH_QUERY: string = 'CHANGE_SEARCH_QUERY';

export const REQUEST_ROBOTS_PENDING: string = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS: string = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILURE: string = 'REQUEST_ROBOTS_FAILURE';